### ISSUE TITLE
sin(2*PI/3+1) is wrong

### ISSUE THREAD

**Issue by certik** [symengine/symengine#1035]
At least in Julia, it returns `sin(1)`.

**Comment by rwst** [comment]
In Python the same.

**Comment by certik** [comment]
Yes, I think it's a bug in C++.

**Comment by rwst** [comment]
The code is written to be very fast, but is limited. The necessary dirty work for it to be usable more generally has not been done. I am also not sure if it is worthwhile to eke out some milliseconds when simplifying trig expressions because it's rarely a repeated task.

If one wants the code to be fixed/extended as it is now for the following simplifications
```
In [1]: sin(2*pi/3+2) 
Out[1]: 
   ⎛π    ⎞
cos⎜─ + 2⎟
   ⎝6    ⎠

In [2]: sin(pi/3+2)   
Out[2]: 
   ⎛π    ⎞
sin⎜─ + 2⎟
   ⎝3    ⎠

In [3]: sin(-pi/3+2)  
Out[3]: 
    ⎛π    ⎞
-cos⎜─ + 2⎟
    ⎝6    ⎠

In [4]: sin(-2*pi/3+2)
Out[4]: 
    ⎛π    ⎞
-sin⎜─ + 2⎟
    ⎝3    ⎠
```
the necessary addition of a modulo 4 case in `eval()` (huh, eval what?) leads to consequences. We can no longer know easily which trig expressions are canonical (probably those with a π shift >=0 and less than π/2).

**Comment by rwst** [comment]
Simply ignoring all π shifts with denominator > 2 will trigger doctests that have been put in place just for the sake of it. Detection of π shifts like the 2/3 above are tested there although, as seen, their handing in the trig functions was not implemented.

**Comment by certik** [comment]
I didn't realize there was a bug in it, so we have to fix it.

I noticed that even the code that we have there is slow, compared to just constructing a sin(x) directly. 

We just need to decide what simplification to do automatically, and what not.

@rwst in your opinion, what would you do automatically when constructing `sin`, and what you would leave as a separate method to simplify?

Personally I was hoping to identify the multiples of `pi` and simplify those, sort of what we do, but fix the bug.

**Comment by rwst** [comment]
You can't identify multiples of `pi` without expanding the argument:
```
In [10]: sin(pi**2-(pi-1)**2)
Out[10]: sin(-(-1 + pi)**2 + pi**2)
```
If you mean identify arguments of form `n*pi` or `a+n*pi` with `n` integer that should be possible fast by writing a more simple version of the helper functions involved. The originals should be left in because of existing doctests, maybe better named. That would be the task for this issue IMHO.

I don't see a problem with including simplification on creation because checking for the existence of `pi` in the argument is fast (tree walk) and the case is rare. Just don't define the canonical form as the fully simplified one. Better define it as the one where arguments of form `n*pi` or `a+n*pi` with `n` integer have been handled, i.e. the above.

**Comment by rwst** [comment]
The outline just given will not work because there are already doctests with a half `pi` shift, so the existing code must be dealt with. First there can still be a rudimentary but fast check in `is_canonical`.

**Comment by rwst** [comment]
Another simple case that is not handled in the code is rational `pi` shifts with absolute value > period like
```
In [3]: sin(13*pi/6+y)
Out[3]: sin(y + (13/6)*pi)
```
It is not necessary to have cases for all denominators, just subtract `pi` or `2*pi` if the coefficient is greater than 1 or 2 and is rational. But that's another ticket.
