### ISSUE TITLE
Print `E` as  `exp(1)` as well.

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine#1225]
`exp(x)` is printed as `exp(x)`
`exp(1)` is printed as `E`. It's better to print it as `exp(1)` for consistency.

**Comment by kanchanarp** [comment]
I would like to work on this.

**Comment by prateeksingh0001** [comment]
Hi, I would like to work on this issue.
@isuruf I'm not able to reproduce the error, on using the expr() function I'm getting an answer of double format like expr(2) gives me an answer of 7.38906. Can you tell me how did you get it ?

**Comment by isuruf** [comment]
@prateeksingh0001, what's `expr(2)`? How did you run your code?

**Comment by prateeksingh0001** [comment]
Sorry for the typo, I ran the `exp()` method in pow.cpp file. I included the symengine library in an external c++ file and then ran it.

**Comment by certik** [comment]
SymPy also prints `E`:
```
In [2]: print exp(-1)
exp(-1)

In [3]: print exp(1)
E

In [4]: print exp(2)
exp(2)
```

**Comment by isuruf** [comment]
Yes, we do the same now. Isn't that inconsistent though?

**Comment by ChrisRackauckas** [comment]
`E` is not a normal thing in Julia. If it used `e` or `exp(1)`, then building functions from the resulting expressions would work. Or if it automatically translated in SymEngine.jl that would be fine. But it currently throws errors whenever it shows up and the place where the function is defined does not have that constant from SymEngine.jl.

**Comment by ChrisRackauckas** [comment]
Don't mean to be pushy, but I would like to bump this because it's tagged as the last issue before the next release. The PR is already prepared, so it's just an issue of whether or not it is a good idea. I was asking for this because Julia doesn't know what `E` is, and this caused issues when handling the output of the differentiation. That was dealt with by adding a Julia printer, so this is no longer a problem. It seems like it'a better choice anyways to allow each of the bound languages handle these types of problems with special printers as other cases likely show up as well, so there's no issue there. Python can just get a printer to make it print out `E` and so what happens here doesn't really matter.

So this really boils down to whether it should print to `E` or `exp(1)` just for C++ usage. In that case, I like the consistency of `exp(1)`, but if there are arguments then I don't see why this would be release-blocking.

**Comment by isuruf** [comment]
Yes, we'll keep the default for Python and have different printers for different languages. I've removed the milestone.
