### ISSUE TITLE
design question: multiple parsers

### ISSUE THREAD

**Issue by lkeegan** [symengine/symengine#1780]
I would like to add a parser for [sbml math](http://model.caltech.edu/software/libsbml/5.18.0/docs/formatted/cpp-api/libsbml-math.html#math-l3) (this is related to #1062 in that what I would like to parse is the infix that libsbml generates from the mathml)

But I'm not sure how to integrate this into symengine.

One way would be to add a `SbmlParser` by copying the contents of `symengine/parser` into e.g. `symengine/parser/sbml`, and making some changes to tokenizer.re, parser.yy, parser.cpp, etc. I have a test branch which has most of the changes required to [tokenizer.re](https://github.com/lkeegan/symengine/compare/master...lkeegan:hack_sbml_parser_support#diff-fff936c4f4c92fd0cb251ee55ab7c4b428c4b1052738c4f212388e0e278336c9), [parser.yy](https://github.com/lkeegan/symengine/compare/master...lkeegan:hack_sbml_parser_support#diff-e959ec029b48e313c44d3448d47fd69f850cc71dbd813633ed89a6a23b7b3d6e) and [parser.cpp](https://github.com/lkeegan/symengine/compare/master...lkeegan:hack_sbml_parser_support#diff-a82e41b56116cef573188a7b62e2f9a3786a735e17a18cec6c2067fd6f3c41ae)

This would be straightforward but involves quite some duplication of code.

Better ideas/suggestions very welcome!..

**Comment by rikardn** [comment]
I like the idea of supporting sbml infix.

My first question is if application specific language parsing should live in symengine or rather in application libraries. I have only briefly worked with sbml, but use many different domain specific languages for pharmaceutical modeling. Parsers for these have been implemented in application libraries like https://github.com/Pharmpy/Pharmpy. Here we use `lark-parser` to parse a fortran-like language and convert into sympy expressions.

I am leaning towards thinking it is a good idea of having sbml infix (and potentially MathML and fortran) parsing in symengine, but not parsing of entire sbml files. I.e. symengine should only focus on reading mathematics from different application formats.

As for your actual question:

I think what you propose is reasonable. If there are helper functions these could be broken out and reused, but otherwise we don't want to entangle the different parsers. The main symengine expression parser should be as fast as possible and we could even consider hand-rolling it in the future for maximum parsing speed. Other parsers might not be as critical.

These are just my five cents and it would be interesting to hear input from team seniors.

**Comment by lkeegan** [comment]
@rikardn thanks for the feedback! I also agree with the idea of parsing math in various formats, but not parsing domain specific languages.

**Comment by rikardn** [comment]
The discussion can be continued in #1785
