### ISSUE TITLE
Incorrect evaluation of relationals

### ISSUE THREAD

**Issue by shivamvats** [symengine/symengine#356]
I tried the following:
```
>>> x = Symbol('x')
>>> x > x + 1
True
>>> x < x + 1
False
```
The simplification obviously gets it wrong. 
I would like to work on this one. I looked into Symbol.compare but it's fine.

**Comment by isuruf** [comment]
`compare` methods are for comparison in dictionaries. Need a new method for comparisons like this.

**Comment by shivamvats** [comment]
How does  CSympy presently deal with inequalities? I see that there is no simplify or solve function.
I'm getting all sorts of funny results like:
```
>>> x = Symbol('x')
>>> x > 4
True
>>> x < 2
False
>>> y = Symbol('y')
>>> x > y
False
```
The relationals are automatically getting simplified to bools, sometimes forcibly and wrongly so. We should prevent such implicit simplification. Could you point me to the file that might be the source of error?

**Comment by isuruf** [comment]
Inequalities are not implemented yet. Neither are assumptions nor logic. [This](https://github.com/sympy/csympy/blob/master/csympy/lib/csympy_wrapper.pyx#L198) is where the comparison is done.

**Comment by thilinarmtb** [comment]
As Isuru mentioned, this functionality is not implemented yet and it is not simple as it seems without knowing what `x` represents. For example, think about complex numbers. Implementing these kind of functionality require a system of assumptions. `SymPy` has been making changes to its assumptions for quite some time now. I don't think we need to redo it. We are more concerned about performance critical areas.

**Comment by shivamvats** [comment]
Oh.
I am mainly worried about the implicit evaluation of the relational to bool,  even when it didn't have the required assumptions to make the simplification, like you said. Till recently, even Sympy would auto simplify such relationals as :  `x > x + 1` to `False`, which it doesn't do now.
Btw, could you tell me about areas that you are currently focusing on? I'd love to get involved.

**Comment by thilinarmtb** [comment]
Well, you are always welcome to contribute !! Off the top of my head, I can think of:
* Only the first idea found [here](https://github.com/sympy/sympy/wiki/gsoc-2014-ideas#detailed-subprojects-in-csympy) was implemented last year during GSOC.
* Polynomial factorization and solutions of polynomial equations

For the moment, these are the only things I can think about.

**Comment by shivamvats** [comment]
Thanks a lot! 
Solutions of polynomial equations seems interesting. I see there is an issue for the solve function. Solution of a linear equation and a system of linear equations could be a starting point for solve. What do you think?

**Comment by certik** [comment]
@shivamvats we follow SymPy in this regard. Once relational functionality is implemented, you would use classes for it like `Lt`, `Gt`, `Eq`. In SymPy, the `==` had to return just True or False for efficiency reasons. But in CSymPy, things are implemented in C++ using classes and things are efficient. The Python wrappers are completely free to use any Python features any way, since their job is to just pass the work down to C++. So we can actually override `<`, `==`, `>` to handle relational functionality. But we should also think about compatibility with SymPy.

**Comment by shivamvats** [comment]
Currently even Sympy doesn't evaluate relationals to booleans:
```
x > x + 1
Out[4]: x > x + 1
```
Not evaluating relationals should thus conform with what Sympy does.

**Comment by rwst** [comment]
I have rewritten Sage's `Expression.__nonzero__` and encountered just the issues that come up here. This is what SymPy's logic module does (e,g. `ask(Q.positive(rel.lhs()-rel.rhs()))`) so should only evaluate if that module is included in symengine. And even then, you want at least two functions, one that applies print order, the other mathematical. The latter will be a drag for performance. But you can't make the former the default either because it's obviously wrong. So don't evaluate at all and let the dev decide which order is wanted in the specific case.

**Comment by rwst** [comment]
With https://github.com/symengine/symengine.py/issues/12 there is the same behaviour as in SymPy, a `sympy.core.relational` being returned (and evaluated). I don't think a symengine relational is highly needed so I guess this ticket can be closed.

**Comment by certik** [comment]
I agree.
