### ISSUE TITLE
Ship optional full BSD version, depend on IMath instead of GMP

### ISSUE THREAD

**Issue by Sumith1896** [symengine/symengine#713]
Dr. Andreas Klöckner(@inducer)  was telling about why LGPL is not comfortable when he wanted to use it in a BSD system and we should probably offer a full BSD version. He suggested that we can depend on libraries like [IMath](https://github.com/creachadair/imath/) to achieve that. Looking up a bit led to the fact that libraries like Integer Set Library([ISL](http://isl.gforge.inria.fr/)) already do that.

An excerpt from their [manual](http://isl.gforge.inria.fr/manual.pdf)

_Note that by default isl requires GMP, which is released under the GNU Lesser General Public License (LGPL). This means that code linked against isl is also linked against LGPL code.When configuring with--with-int=imath, isl will link against imath, a library for exact integer arithmetic released under the MIT license._

We need something similar. We can follow ISL on this but there is one issue.
IMath lacks `mpz_gcd` and `mpz_lcm` (atleast for what I have looked at) which our `ntheory` module heavily depends on. So, how do we go about?

**Comment by certik** [comment]
We should definitely lift the hard dependency on GMP and allow to optionally use IMath (I didn't know about it until @Sumith1896 pointed it to me). I think by default we should still use GMP, because that offers the best performance. But optionally we should definitely allow IMath and possibly other integer libraries like https://github.com/wbhart/bsdnt

The way to do it is to fix #478. I.e. have our own class, and just use the C interface to gmp. And then we can easily use another C interface to IMath or bsdnt. Another (equivalent) look at it is to simply require a certain C++ class, and allow (perhaps using a template) any other class to be used instead. That way we can add other integer implementations in the future. 

This is also related to our efforts to use `piranha::integer`, which should actually be faster for small integers than our current `mpz_class` from GMP. 

So for all these reasons, we need to do this.

**Comment by isuruf** [comment]
[Boost.multiprecision](http://www.boost.org/doc/libs/master/libs/multiprecision/doc/html/index.html) has rational classes and floats and might be a better option than IMath or bsdnt

**Comment by isuruf** [comment]
Closed via #1121

**Comment by certik** [comment]
SymEngine now doesn't depend on GMP, thanks to @ivme and @isuruf.

**Comment by inducer** [comment]
Awesome! Thank you for making this possible.
